baseURL: https://6yardscreamers.netlify.app
defaultContentLanguage: en
theme: FeelIt
title: 6YS
enableRobotsTXT: yes
enableGitInfo: yes
enableEmoji: yes
googleAnalytics: ''
ignoreErrors:
  - err-missing-comment-accesstoken
  - err-missing-oembed-accesstoken
languages:
  en:
    copyright: This work is licensed under a Creative Commons Attribution-NonCommercial
      4.0 International License.
    hasCJKLanguage: no
    languageCode: en
    languageName: English
    menu:
      main:
        - identifier: posts
          name: Posts
          post: ''
          pre: <i class='fa fa-futbol fa-fw'></i>
          title: ''
          url: /posts/
          weight: 1
        - identifier: tags
          name: Tags
          post: ''
          pre: ''
          title: ''
          url: /tags/
          weight: 2
        - identifier: categories
          name: Categories
          post: ''
          pre: ''
          title: ''
          url: /categories/
          weight: 3
        - identifier: about
          name: About
          post: ''
          pre: ''
          title: ''
          url: /about/
          weight: 4
        - identifier: twitter
          name: ''
          post: ''
          pre: <i class='fab fa-twitter fa-fw'></i>
          title: Twitter
          url: https://twitter.com/6yardscreamers
          weight: 5
        - identifier: Mastodon
          name: ''
          post: ''
          pre: <i class='fab fa-mastodon fa-fw'></i>
          title: Mastodon
          url: https://mastodon.skrimmage.com/@Christina
          weight: 6
    paginate: 12
    params:
      about:
        description: "Welcome to my blog where you'll mostly find some of my thoughts and ideas about football <i class='fas fa-futbol'></i>.   Some of my professional experience includes: <i class='fas fa-ruler'></i> psychometrics, <i class='fas fa-brain'></i> clinical psychology, <i class='far fa-chart-bar'></i> data analysis and football performance analysis. You can also find me <i class='fab fa-twitter'></i> **[here](https://www.twitter.com/6yardscreamers)** and <i class='fab fa-mastodon'></i> **[here](https://mastodon.skrimmage.com/@Christina)** . To get in touch, please send to: 6ysblog@gmail.com" 
        enable: yes
        param: yes
        paramTitle: Attributes
        parameter:
          - language: Shirt Tucking
            level: '20'
          - language: Footedness (Right)
            level: '89'
          - language: Sock Height
            level: '60'
        status:
          - desc: She/Her
            faIcon: far fa-id-card
            title: Pronouns
          - desc: English/French
            faIcon: far fa-comment
            title: Languages
          - desc: Canada
            faIcon: fas fa-map-marker-alt
            title: Location
      app:
        iconColor: '#5bbad5'
        noFavicon: no
        svgFavicon: ''
        themeColor: '#ffffff'
        tileColor: '#da532c'
        title: 6yardscreamers
      description: About Christina
      home:
        posts:
          enable: yes
          imagePreview: yes
          paginate: 6
        profile:
          avatarURL: /images/profile_1.png
          disclaimer: ''
          enable: yes
          gravatarEmail: ''
          social: yes
          subtitle: "Mostly data driven reflections on football"
          title: "- - - - -"
          typeit: yes
        rss: 10
      keywords:
        - Theme
        - Hugo
      search:
        absoluteURL: no
        algolia:
          appID: UAL0NNJWXE
          index: index.en
          searchKey: 7b7fbdfb7ee82ee61901f2c6b09b05be
        contentLength: 4000
        enable: no
        highlightTag: em
        maxResultLength: 10
        placeholder: ''
        snippetLength: 30
        type: algolia
    weight: 1
params:
  SourceMap: no
  analytics:
    enable: no
    fathom:
      id: ''
      server: ''
    goatcounter:
      code: ''
  cdn:
    data: jsdelivr.yml
  compatibility:
    objectFit: no
    polyfill: no
  cookieconsent:
    content:
      dismiss: ''
      link: ''
      message: ''
    enable: no
  dateFormat: '2006-01-02'
  defaultTheme: auto
  fingerprint: ''
  footer:
    author: yes
    copyright: yes
    custom: ''
    enable: yes
    hugo: yes
    icp: ''
    license: <a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/"
      target="_blank">CC BY-NC 4.0</a>
    since: 2022
  gitRepo: 
  header:
    desktopMode: fixed
    mobileMode: auto
    title:
      logo: ''
      name: 6YS
      post: ''
      pre: <i class='fas fa-futbol fas'></i>
      rss: no
      typeit: no
  images: /logo.png
  list:
    dateFormat: 01-02
    paginate: 20
    rss: 10
  oembed:
    facebook:
      accessToken: ''
    privacy: no
    twitter:
      enableDNT: yes
  page:
    cdnfontawesome: yes
    code:
      copy: yes
      maxShownLines: 10
    comment:
      commento:
        enable: no
      disqus:
        enable: no
        shortname: ''
      enable: yes
      facebook:
        appId: ''
        enable: no
        languageCode: ''
        numPosts: 10
        width: 100%
      gitalk:
        clientId: ''
        clientSecret: ''
        enable: no
        owner: ''
        repo: ''
      telegram:
        color: ''
        colorful: yes
        dislikes: no
        enable: no
        height: ''
        limit: 5
        outlined: no
        siteID: ''
      utterances:
        darkTheme: github-dark
        enable: no
        issueTerm: pathname
        label: ''
        lightTheme: github-light
        repo: ''
      valine:
        appId: QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI
        appKey: WBmoGyJtbqUswvfLh6L8iEBr
        avatar: mp
        emoji: ''
        enable: no
        enableQQ: no
        highlight: yes
        lang: ''
        meta: ''
        pageSize: 10
        placeholder: ''
        recordIP: yes
        serverURLs: 
        visitor: yes
      vssue:
        clientId: 85f66799bb256a5064be
        clientSecret: ''
        enable: yes
        owner: khusika
        platform: github
        repo: comments
    fontawesome: yes
    fraction: yes
    hiddenFromHomePage: no
    hiddenFromSearch: no
    improveArticle: 
    library:
      css: {}
      js: {}
    lightgallery: no
    linkToMarkdown: yes
    mapbox:
      accessToken: pk.eyJ1IjoiZGlsbG9uenEiLCJhIjoiY2s2czd2M2x3MDA0NjNmcGxmcjVrZmc2cyJ9.aSjv2BNuZUfARvxRYjSVZQ
      darkStyle: mapbox://styles/mapbox/dark-v10?optimize=true
      fullscreen: yes
      geolocate: yes
      lightStyle: mapbox://styles/mapbox/light-v10?optimize=true
      navigation: yes
      scale: yes
    math:
      blockLeftDelimiter: ''
      blockRightDelimiter: ''
      copyTex: yes
      enable: no
      inlineLeftDelimiter: ''
      inlineRightDelimiter: ''
      mhchem: yes
    rssFullText: no
    ruby: yes
    seo:
      images: []
      publisher:
        logoUrl: /images/avatar.webp
        name: xxxx
    share:
      Baidu: no
      Blogger: no
      Buffer: no
      Digg: no
      Evernote: no
      Facebook: no
      Flipboard: no
      HackerNews: no
      Instapaper: no
      Line: no
      Linkedin: no
      Mix: no
      Myspace: no
      Odnoklassniki: no
      Pinterest: no
      Pocket: no
      Reddit: no
      Renren: no
      Skype: no
      Stumbleupon: no
      Trello: no
      Tumblr: no
      Twitter: yes
      VK: no
      Weibo: no
      Whatsapp: no
      Xing: no
      enable: no
    toc:
      auto: yes
      enable: yes
      keepStatic: no
    twemoji: no
  pwa:
    enable: yes
    version: 1.0.1
  section:
    dateFormat: 01-02
    paginate: 20
    rss: 10
  seo:
    image: /images/Apple-Devices-Preview.webp
    thumbnailUrl: /images/screenshot.png
  social:
    Angellist: ''
    Bandcamp: ''
    Behance: ''
    Bilibili: ''
    Bitbucket: ''
    Codepen: ''
    Deviantart: ''
    Devto: ''
    Douban: ''
    Dribbble: ''
    Email: '6ysblog@gmail.com'
    Facebook: ''
    Fivehundredpx: ''
    Flickr: ''
    Foursquare: ''
    FreeCodeCamp: ''
    GitHub: ''    
    Gitea: ''
    Gitlab: ''
    Goodreads: ''
    Googlescholar: ''
    Hackernews: ''
    Instagram: ''
    Jsfiddle: ''
    Keybase: ''
    Kickstarter: ''
    Lastfm: ''
    Linkedin: ''
    Mastodon:
      id: '@Christina'
      prefix: 'https://mastodon.skrimmage.com/'
    Matrix: ''
    Medium: ''
    Mix: ''
    Odnoklassniki: ''
    Patreon: ''
    Paypal: ''
    Pinterest: ''
    Quora: ''
    RSS: no
    Reddit: ''
    Researchgate: ''
    Resume: ''
    Skype: ''
    Slidershare: ''
    Snapchat: ''
    Soundcloud: ''
    Spotify: ''
    Stackoverflow: ''
    Steam: ''
    Strava: ''
    Telegram: ''
    Thingiverse: ''
    Tumblr: ''
    Twitch: ''
    Twitter: 6yardscreamers
    VK: ''
    Vine: ''
    Weibo: ''
    Whatsapp: ''
    Wordpress: ''
    XMPP: ''
    Xing: ''
    Youtubechannel: ''
    Youtubecustom: ''
    Youtubelegacy: ''
    Zhihu: ''
    xda: ''
  typeit:
    cursorChar: '|'
    cursorSpeed: 1000
    duration: -1
    speed: 100
  verification:
    baidu: ''
    bing: ''
    google: ''
    pinterest: ''
    yandex: ''
  version: 1.0.X
markup:
  goldmark:
    extensions:
      definitionList: yes
      footnote: yes
      linkify: yes
      strikethrough: yes
      table: yes
      taskList: yes
      typographer: yes
    renderer:
      unsafe: yes
  highlight:
    codeFences: yes
    guessSyntax: yes
    lineNos: yes
    lineNumbersInTable: yes
    noClasses: no
  tableOfContents:
    endLevel: 6
    startLevel: 2
author:
  email: ''
  link: ''
  name: .
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
Permalinks:
  posts: :filename
privacy:
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
    useSessionStorage: no
  instagram: {}
  twitter:
    enableDNT: yes
  youtube:
    privacyEnhanced: yes
mediaTypes:
  text/plain:
    suffixes: md
outputFormats:
  MarkDown:
    isHTML: no
    isPlainText: yes
    mediaType: text/plain
outputs:
  home:
    - HTML
    - RSS
    - JSON
  page:
    - HTML
    - MarkDown
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm: HTML
